POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "partner1@user.com",
    "password": "secret"
}

###
POST http://localhost:3000/partners
Content-Type: application/json

{
    "name": "Partner 1",
    "email": "partner1@user.com",
    "password": "secret",
    "company_name": "Company Name 1"
}

POST http://localhost:3000/partners/events
Content-Type: application/json

{
    "name": "Partner 1",
    "email": "partner1@user.com",
    "password": "secret",
    "company_name": "Company Name 1"
}

###
GET http://localhost:3000/partners/events

###
GET http://localhost:3000/partners/events/1

###
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Evento teste 1",
    "description": "descrição do evento",
    "date": "2021-01-01T00:00:00",
    "location": "Rua x, bairro etc"
}

###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/1

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Partner 1",
    "email": "partner1@user.com",
    "password": "secret",
    "address": "adress test",
    "phone": "33333333333"
}