services:
  mysql:
    image: mysql:8.0.30-debian
    container_name: ticket-sales-db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    ports:
      - "3306:3306"

    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
